FROM nginx:1.15.3-alpine
RUN apk add --no-cache inotify-tools
RUN wget -q https://github.com/krallin/tini/releases/download/v0.18.0/tini-static -O /sbin/tini && chmod +x /sbin/tini
RUN rm /etc/nginx/nginx.conf.default
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY run.sh /root/run.sh
ENTRYPOINT ["/sbin/tini", "-e 143", "/root/run.sh"]
