# Production deployment
version: '3'
services:
  api:
    build: ./api
    restart: on-failure
    links:
      - db:db
    environment:
      - FLASK_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  app:
    build: ./app
    volumes:
      - dist:/code/dist
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  http:
    build: ./http
    restart: on-failure
    ports:
      - 80:80
    links:
      - api:api
      - app:app
    volumes:
      - dist:/dist
volumes:
  pgdata:
  dist:
