FROM postgres:11-alpine
ARG USDS_URL=http://www.ars.usda.gov/ARSUserFiles/80400525/Data/BFPDB/BFPD_csv_07132018.zip
ARG SEED_FILE=seed.zip
ADD $USDS_URL $SEED_FILE
RUN unzip -q $SEED_FILE && chmod 777 *.csv
COPY *.sql *.sh /docker-entrypoint-initdb.d/
EXPOSE 5432
